/* Unflattening a grammar: turn word lists into OpenSCAD source for two
   printable objects from the talk (Act III): a word cryptex, where each ring is
   one slot of a sentence, and a flower spinner, where two rings of petals pair
   words at a pointer. Pure string building, so it runs in node (tests, the
   tools/ script) and in the browser (the p5 preview's download button).
   These are simplified teaching models, not Emily's remixed MakerWorld files. */
(function (root) {
  'use strict';

  const q = (s) => '"' + String(s).replace(/\\/g, '\\\\').replace(/"/g, '\\"') + '"';
  const list = (words) => '[' + words.map(q).join(', ') + ']';
  const nested = (lists) => '[\n' + lists.map((l) => '  ' + list(l)).join(',\n') + '\n]';

  // Pull ring order out of a Tracery grammar: the symbols in origin, left to right.
  function slotsFromGrammar(grammar) {
    const origin = [].concat(grammar.origin || [])[0] || '';
    const names = [...origin.matchAll(/#([A-Za-z0-9_]+)(?:\.[A-Za-z.]+)?#/g)].map((m) => m[1]);
    return names.map((name) => ({ name, words: [].concat(grammar[name] || []).map(String) }));
  }

  function checkSlots(slots) {
    const errors = [];
    if (slots.length < 2) errors.push('origin needs at least two #symbols#, one per ring');
    slots.forEach((s) => {
      if (!s.words.length) errors.push(`#${s.name}# has no words`);
      if (s.words.some((w) => /#|\[/.test(w))) errors.push(`#${s.name}# words must be plain text: a printed face cannot expand a rule`);
    });
    const n = slots.length ? slots[0].words.length : 0;
    if (slots.some((s) => s.words.length !== n)) errors.push('every ring needs the same number of words (one per face)');
    if (n && (n < 3 || n > 16)) errors.push('use 3 to 16 words per ring');
    return errors;
  }

  // Ring length in mm: ~3.3 mm per bold character at 4.5 mm, plus a margin.
  function ringLength(slots) {
    const longest = Math.max(...slots.flatMap((s) => s.words.map((w) => w.length)));
    return Math.max(24, Math.ceil(longest * 3.4 + 6));
  }

  function cryptex(slots) {
    const ringLen = ringLength(slots);
    return `// Grammar cryptex: each ring is one slot of the sentence, each face one word.
// Generated by the Unmaking workshop (workshop/js/scad.js). Edit freely.
// Slots, in reading order: ${slots.map((s) => '#' + s.name + '#').join(' ')}
//
// A teaching model: the rings spin freely on a core between two caps. It has no
// lock gates or detents. For a clicking cryptex, remix a published design and
// credit it (the talk's print remixes two CC BY-NC designs from MakerWorld).
// Print: PLA, 0.2 mm layers, rings standing on end, no supports.
// Render one part at a time by setting part, then F6 and export STL.

words = ${nested(slots.map((s) => s.words))};

part       = "print";   // "print" = every part laid flat, "preview" = assembled, "rings", "core", "cap"
faces      = len(words[0]);
text_size  = 4.5;       // mm, cap height of each word
text_depth = 0.8;       // mm, how deep words are recessed
ring_len   = ${ringLen};        // mm along the axis; grow it if your longest word runs off the face
face_w     = 9;         // mm across one face
gap        = 0.6;       // mm between rings on the core
core_d     = 12;        // mm, diameter of the core rod
clearance  = 0.5;       // mm per side; raise it if rings bind, lower it if they wobble
cap_len    = 8;         // mm
font       = "Liberation Sans:style=Bold";

R       = face_w / (2 * sin(180 / faces));  // circumradius of the ring
apothem = R * cos(180 / faces);             // centre to the middle of a face
rings   = len(words);
rod_len = rings * (ring_len + gap) + cap_len / 2;

// One ring of the grammar. Word i sits on the face at angle i * 360 / faces,
// reading along the axis, so a row of faces across the rings reads as a sentence.
module word_ring(ws) {
  difference() {
    rotate([0, 0, 180 / faces]) cylinder(r = R, h = ring_len, $fn = faces);
    translate([0, 0, -1]) cylinder(d = core_d + 2 * clearance, h = ring_len + 2, $fn = 64);
    for (i = [0 : faces - 1])
      rotate([0, 0, i * 360 / faces])
        // text x -> along the axis, text y -> around the ring, extrude -> outward
        multmatrix([[0, 0, 1, apothem - text_depth], [0, -1, 0, 0], [1, 0, 0, ring_len / 2], [0, 0, 0, 1]])
          linear_extrude(text_depth + 1)
            text(ws[i], size = text_size, font = font, halign = "center", valign = "center");
  }
}

// Bottom cap and rod in one piece.
module core() {
  cylinder(r = R, h = cap_len, $fn = 64);
  cylinder(d = core_d, h = cap_len + rod_len, $fn = 64);
}

// Top cap: a snug socket. A drop of glue makes it permanent.
module cap() {
  difference() {
    cylinder(r = R, h = cap_len, $fn = 64);
    translate([0, 0, 2]) cylinder(d = core_d + 0.15, h = cap_len, $fn = 64);
  }
}

module print_layout() {
  pitch = 2 * R + 6;
  for (r = [0 : rings - 1]) translate([r * pitch, 0, 0]) word_ring(words[r]);
  translate([rings * pitch, 0, 0]) core();
  translate([(rings + 1) * pitch, 0, 0]) cap();
}

module preview() {
  color("navy") core();
  for (r = [0 : rings - 1])
    color(r % 2 ? "teal" : "powderblue")
      translate([0, 0, cap_len + gap / 2 + r * (ring_len + gap)]) word_ring(words[r]);
  color("navy") translate([0, 0, 2 * cap_len + rings * (ring_len + gap)]) rotate([180, 0, 0]) cap();
}

if (part == "print") print_layout();
else if (part == "preview") preview();
else if (part == "rings") for (r = [0 : rings - 1]) translate([r * (2 * R + 6), 0, 0]) word_ring(words[r]);
else if (part == "core") core();
else if (part == "cap") cap();
`;
  }

  function spinner(outer, inner) {
    // Size petals to the longest word (~3 mm per bold character at 4 mm), inner ring first.
    const fit = (words) => Math.ceil(Math.max(...words.map((w) => String(w).length)) * 3 + 6);
    const innerLen = fit(inner), outerLen = fit(outer);
    const innerDist = 11 + innerLen / 2 - 3;
    const outerDist = innerDist + innerLen / 2 + outerLen / 2 + 1;
    return `// Flower spinner: two rings of petals turn on one post; the pointer pairs a
// word from each ring. Generated by the Unmaking workshop (workshop/js/scad.js).
// A teaching model: base with post, two petal layers, and a press-fit knob
// with a pointer arm. Print: PLA, 0.2 mm layers, every part flat side down.
// Set part to "base", "outer", "inner" and "knob" in turn and export one STL each.

outer_words = ${list(outer)};
inner_words = ${list(inner)};

part       = "preview"; // "preview", "base", "outer", "inner", "knob"
text_size  = 4;         // mm
text_depth = 0.8;       // mm
layer_t    = 3.2;       // mm, thickness of each petal layer
post_d     = 10;        // mm
clearance  = 0.4;       // mm per side around the post
font       = "Liberation Sans:style=Bold";

// Petal centre distance, length (sized to the longest word) and width, in mm.
// The outer petals start where the inner ones end, so no word is covered.
outer_dist = ${outerDist};  outer_len = ${outerLen};  outer_w = 16;
inner_dist = ${innerDist};  inner_len = ${innerLen};  inner_w = 13;
hub_d      = 22;
base_d     = 2 * (outer_dist + outer_len / 2) + 4;
base_t     = 3;

module petal(pl, pw) { scale([pl / pw, 1, 1]) circle(d = pw, $fn = 48); }

// A layer of petals with one word on each, written outward from the centre.
// The disc joins the petals to the hub; the outer layer's disc carries the inner layer.
module petal_layer(ws, dist, pl, pw) {
  n = len(ws);
  difference() {
    linear_extrude(layer_t) union() {
      circle(r = max(hub_d / 2, dist - pl / 2 + 2), $fn = 96);
      for (i = [0 : n - 1]) rotate(i * 360 / n) translate([dist, 0]) petal(pl, pw);
    }
    translate([0, 0, -1]) cylinder(d = post_d + 2 * clearance, h = layer_t + 2, $fn = 64);
    for (i = [0 : n - 1])
      rotate(i * 360 / n) translate([dist, 0, layer_t - text_depth])
        linear_extrude(text_depth + 1)
          text(ws[i], size = text_size, font = font, halign = "center", valign = "center");
  }
}

module base() {
  cylinder(d = base_d, h = base_t, $fn = 96);
  cylinder(d = post_d, h = base_t + 2 * layer_t + 1 + 6, $fn = 64);
}

// Knob with a pointer arm that reaches over both rings.
module knob() {
  difference() {
    union() {
      cylinder(d = hub_d, h = 6, $fn = 64);
      translate([0, -2.5, 0]) cube([outer_dist + outer_len / 2, 5, 2]);
    }
    translate([0, 0, -1]) cylinder(d = post_d + 0.15, h = 5, $fn = 64);
  }
}

module preview() {
  color("black") base();
  color("palegreen") translate([0, 0, base_t]) petal_layer(outer_words, outer_dist, outer_len, outer_w);
  color("lightgreen") translate([0, 0, base_t + layer_t + 0.5]) petal_layer(inner_words, inner_dist, inner_len, inner_w);
  color("black") translate([0, 0, base_t + 2 * layer_t + 1 + 6 - 4]) knob();  // socket slides 4 mm onto the post
}

if (part == "preview") preview();
else if (part == "base") base();
else if (part == "outer") petal_layer(outer_words, outer_dist, outer_len, outer_w);
else if (part == "inner") petal_layer(inner_words, inner_dist, inner_len, inner_w);
else if (part == "knob") knob();
`;
  }

  const api = { slotsFromGrammar, checkSlots, ringLength, cryptex, spinner };
  if (typeof module === 'object' && module.exports) module.exports = api;
  else root.Scad = api;
})(globalThis);
