// Grammar cryptex: each ring is one slot of the sentence, each face one word.
// Generated by the Unmaking workshop (workshop/js/scad.js). Edit freely.
// Slots, in reading order: #who# #when# #does# #how#
//
// A teaching model: the rings spin freely on a core between two caps. It has no
// lock gates or detents. For a clicking cryptex, remix a published design and
// credit it (the talk's print remixes two CC BY-NC designs from MakerWorld).
// Print: PLA, 0.2 mm layers, rings standing on end, no supports.
// Render one part at a time by setting part, then F6 and export STL.

words = [
  ["the agent", "a quilter", "my bot", "the archive", "a student", "the machine", "our zine", "the cursor"],
  ["always", "never", "slowly", "quietly", "sometimes", "rarely", "gladly", "still"],
  ["unravels", "remembers", "stitches", "forgets", "loops", "glitches", "listens", "wanders"],
  ["by hand", "offline", "in public", "at night", "for us", "in loops", "on paper", "elsewhere"]
];

part       = "print";   // "print" = every part laid flat, "preview" = assembled, "rings", "core", "cap"
faces      = len(words[0]);
text_size  = 4.5;       // mm, cap height of each word
text_depth = 0.8;       // mm, how deep words are recessed
ring_len   = 44;        // mm along the axis; grow it if your longest word runs off the face
face_w     = 9;         // mm across one face
gap        = 0.6;       // mm between rings on the core
core_d     = 12;        // mm, diameter of the core rod
clearance  = 0.5;       // mm per side; raise it if rings bind, lower it if they wobble
cap_len    = 8;         // mm
font       = "Liberation Sans:style=Bold";

R       = face_w / (2 * sin(180 / faces));  // circumradius of the ring
apothem = R * cos(180 / faces);             // centre to the middle of a face
rings   = len(words);
rod_len = rings * (ring_len + gap) + cap_len / 2;

// One ring of the grammar. Word i sits on the face at angle i * 360 / faces,
// reading along the axis, so a row of faces across the rings reads as a sentence.
module word_ring(ws) {
  difference() {
    rotate([0, 0, 180 / faces]) cylinder(r = R, h = ring_len, $fn = faces);
    translate([0, 0, -1]) cylinder(d = core_d + 2 * clearance, h = ring_len + 2, $fn = 64);
    for (i = [0 : faces - 1])
      rotate([0, 0, i * 360 / faces])
        // text x -> along the axis, text y -> around the ring, extrude -> outward
        multmatrix([[0, 0, 1, apothem - text_depth], [0, -1, 0, 0], [1, 0, 0, ring_len / 2], [0, 0, 0, 1]])
          linear_extrude(text_depth + 1)
            text(ws[i], size = text_size, font = font, halign = "center", valign = "center");
  }
}

// Bottom cap and rod in one piece.
module core() {
  cylinder(r = R, h = cap_len, $fn = 64);
  cylinder(d = core_d, h = cap_len + rod_len, $fn = 64);
}

// Top cap: a snug socket. A drop of glue makes it permanent.
module cap() {
  difference() {
    cylinder(r = R, h = cap_len, $fn = 64);
    translate([0, 0, 2]) cylinder(d = core_d + 0.15, h = cap_len, $fn = 64);
  }
}

module print_layout() {
  pitch = 2 * R + 6;
  for (r = [0 : rings - 1]) translate([r * pitch, 0, 0]) word_ring(words[r]);
  translate([rings * pitch, 0, 0]) core();
  translate([(rings + 1) * pitch, 0, 0]) cap();
}

module preview() {
  color("navy") core();
  for (r = [0 : rings - 1])
    color(r % 2 ? "teal" : "powderblue")
      translate([0, 0, cap_len + gap / 2 + r * (ring_len + gap)]) word_ring(words[r]);
  color("navy") translate([0, 0, 2 * cap_len + rings * (ring_len + gap)]) rotate([180, 0, 0]) cap();
}

if (part == "print") print_layout();
else if (part == "preview") preview();
else if (part == "rings") for (r = [0 : rings - 1]) translate([r * (2 * R + 6), 0, 0]) word_ring(words[r]);
else if (part == "core") core();
else if (part == "cap") cap();
