// Flower spinner: two rings of petals turn on one post; the pointer pairs a
// word from each ring. Generated by the Unmaking workshop (workshop/js/scad.js).
// A teaching model: base with post, two petal layers, and a press-fit knob
// with a pointer arm. Print: PLA, 0.2 mm layers, every part flat side down.
// Set part to "base", "outer", "inner" and "knob" in turn and export one STL each.

outer_words = ["DH", "Making", "Play", "Pedagogy", "Tech Comm", "Archives"];
inner_words = ["Twine", "Tracery", "p5.js", "Agents", "Bitsy", "Zines"];

part       = "preview"; // "preview", "base", "outer", "inner", "knob"
text_size  = 4;         // mm
text_depth = 0.8;       // mm
layer_t    = 3.2;       // mm, thickness of each petal layer
post_d     = 10;        // mm
clearance  = 0.4;       // mm per side around the post
font       = "Liberation Sans:style=Bold";

// Petal centre distance, length (sized to the longest word) and width, in mm.
// The outer petals start where the inner ones end, so no word is covered.
outer_dist = 52.5;  outer_len = 33;  outer_w = 16;
inner_dist = 21.5;  inner_len = 27;  inner_w = 13;
hub_d      = 22;
base_d     = 2 * (outer_dist + outer_len / 2) + 4;
base_t     = 3;

module petal(pl, pw) { scale([pl / pw, 1, 1]) circle(d = pw, $fn = 48); }

// A layer of petals with one word on each, written outward from the centre.
// The disc joins the petals to the hub; the outer layer's disc carries the inner layer.
module petal_layer(ws, dist, pl, pw) {
  n = len(ws);
  difference() {
    linear_extrude(layer_t) union() {
      circle(r = max(hub_d / 2, dist - pl / 2 + 2), $fn = 96);
      for (i = [0 : n - 1]) rotate(i * 360 / n) translate([dist, 0]) petal(pl, pw);
    }
    translate([0, 0, -1]) cylinder(d = post_d + 2 * clearance, h = layer_t + 2, $fn = 64);
    for (i = [0 : n - 1])
      rotate(i * 360 / n) translate([dist, 0, layer_t - text_depth])
        linear_extrude(text_depth + 1)
          text(ws[i], size = text_size, font = font, halign = "center", valign = "center");
  }
}

module base() {
  cylinder(d = base_d, h = base_t, $fn = 96);
  cylinder(d = post_d, h = base_t + 2 * layer_t + 1 + 6, $fn = 64);
}

// Knob with a pointer arm that reaches over both rings.
module knob() {
  difference() {
    union() {
      cylinder(d = hub_d, h = 6, $fn = 64);
      translate([0, -2.5, 0]) cube([outer_dist + outer_len / 2, 5, 2]);
    }
    translate([0, 0, -1]) cylinder(d = post_d + 0.15, h = 5, $fn = 64);
  }
}

module preview() {
  color("black") base();
  color("palegreen") translate([0, 0, base_t]) petal_layer(outer_words, outer_dist, outer_len, outer_w);
  color("lightgreen") translate([0, 0, base_t + layer_t + 0.5]) petal_layer(inner_words, inner_dist, inner_len, inner_w);
  color("black") translate([0, 0, base_t + 2 * layer_t + 1 + 6 - 4]) knob();  // socket slides 4 mm onto the post
}

if (part == "preview") preview();
else if (part == "base") base();
else if (part == "outer") petal_layer(outer_words, outer_dist, outer_len, outer_w);
else if (part == "inner") petal_layer(inner_words, inner_dist, inner_len, inner_w);
else if (part == "knob") knob();
